-- MySQL Script generated by MySQL Workbench
-- Fri Nov 13 19:27:45 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`sites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sites` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `adresse` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `nombres_secteurs` INT(11) NOT NULL,
  `est_taguer` TINYINT(4) NOT NULL,
  `sitescol` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prénom` VARCHAR(45) NULL DEFAULT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `téléphone` INT(11) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`commentaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`commentaire` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `sites_id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `message` VARCHAR(255) NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Sites_has_User_User1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_Sites_has_User_Sites1_idx` (`sites_id` ASC) VISIBLE,
  CONSTRAINT `fk_Sites_has_User_Sites1`
    FOREIGN KEY (`sites_id`)
    REFERENCES `mydb`.`sites` (`id`),
  CONSTRAINT `fk_Sites_has_User_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`secteur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`secteur` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  `nombres_voies` INT(11) NOT NULL,
  `sites_id` INT(11) NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Secteur_Sites1_idx` (`sites_id` ASC) VISIBLE,
  CONSTRAINT `fk_Secteur_Sites1`
    FOREIGN KEY (`sites_id`)
    REFERENCES `mydb`.`sites` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`voies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`voies` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cotations` VARCHAR(45) NULL DEFAULT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `nombres_relais` INT(11) NOT NULL,
  `points` INT(11) NOT NULL,
  `secteur_id` INT(11) NOT NULL,
  `longueur` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Voies_Secteur1_idx` (`secteur_id` ASC) VISIBLE,
  CONSTRAINT `fk_Voies_Secteur1`
    FOREIGN KEY (`secteur_id`)
    REFERENCES `mydb`.`secteur` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`longeur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`longeur` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cotation` VARCHAR(45) NOT NULL,
  `voies_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_table2_Voies1_idx` (`voies_id` ASC) VISIBLE,
  CONSTRAINT `fk_table2_Voies1`
    FOREIGN KEY (`voies_id`)
    REFERENCES `mydb`.`voies` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`topo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`topo` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL DEFAULT NULL,
  `lieux` VARCHAR(45) NULL DEFAULT NULL,
  `date_parution` VARCHAR(45) NULL DEFAULT NULL,
  `nombres_disponibles` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Topo_User1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_Topo_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`réservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`réservation` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `topo_id` INT(11) NOT NULL,
  `message` VARCHAR(500) NULL DEFAULT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_User_has_Topo_Topo1_idx` (`topo_id` ASC) VISIBLE,
  INDEX `fk_User_has_Topo_User1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_Topo_Topo1`
    FOREIGN KEY (`topo_id`)
    REFERENCES `mydb`.`topo` (`id`),
  CONSTRAINT `fk_User_has_Topo_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`split`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`split` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `numéro` VARCHAR(45) NOT NULL,
  `longeur_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Split_Longeur1_idx` (`longeur_id` ASC) VISIBLE,
  CONSTRAINT `fk_Split_Longeur1`
    FOREIGN KEY (`longeur_id`)
    REFERENCES `mydb`.`longeur` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
